from . import gelato_image_frame
from . import gelato_delivery_box
from . import gelato_customer
from . import gelato_delivery_zone
from . import gelato_geocode
from . import gelato_delivery_addon
from . import gelato_promo_code
from . import gelato_delivery_order
from . import website
from . import res_config_settings
from . import ir_http
